version: '3'

services:
  example:
    image: ghost:1-alpine
    restart: always
    ports:
      - 2368:2368
    environment:
      database__client: mysql
      database__connection__database: ghost
      database__connection__host: database
      database__connection__user: root
      database__connection__password: password
    depends_on:
      - database
  database:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: password
      # - MYSQL_ROOT_PASSWORD=password
